insert dbo.category(name , describe ,slug)
values ('Bakery','Bakery','bakery')
insert dbo.category(name , describe ,slug)
values ('Fruit & Vegetable','Fruit & Vegetable','fruit')
insert dbo.category(name , describe ,slug)
values ('Meet & Fish','Meet & Fish','meet')
insert dbo.category(name , describe ,slug)
values ('Drinks','Drinks','drink')
insert dbo.category(name , describe ,slug)
values ('Kitchen','Kitchen','kitchen')
insert dbo.category(name , describe ,slug)
values ('Special Nutrition','Special Nutrition','nutrition')
insert dbo.category(name , describe ,slug)
values ('Baby','Baby','baby')
insert dbo.category(name , describe ,slug)
values ('Pharmacy','Pharmacy','pharmacy')

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pancake','Pancake','pancake',101)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Muffins','Muffins','muffins',101)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Scornes','Scornes','scornes',101)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Bread','Bread','bread',101)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Bagel','Bagel','bagel',101)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pizza','Pizza','pizza',101)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Cookie','Cookie','cookie',101)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Vegetable','Vegetable','vegetable',102)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Fruit','Fruit','fruit',102)


insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Beef & Lamb','Beef & Lamb','beef-lamb',103)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Chicken','Chicken','chicken',103)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pork','Pork','pork',103)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Seafood','Seafood','seafood',103)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Organic','Organic','organic',103)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Bacon','Bacon','bacon',103)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Hot Dog & Sausage','Hot Dog & Sausage','hotdog-sausage',103)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Water','Water','water',104)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Soft Drinks','Soft Drinks','soft-drinks',104)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Fruit Juice','Fruit Juice','fruit-juice',104)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Sport Drinks','Sport Drinks','sport-drinks',104)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Energy Drinks','Energy Drinks','energy-drink',104)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Tea','Tea','tea',104)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Chocolate & Cocoa','Chocolate & Cocoa','chocolate-cocoa',104)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Cocktail','Cocktail','cocktail',104)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Chilled Beverages','Chilled Beverages','chilled-beverages',104)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Kitchen Appliances','Kitchen Appliances','kitchen-appliances',105)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Dining','Dining','dining',105)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pots & Pans','Pots & Pans','pots-pans',105)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Tools & Gadgets','Tools & Gadgets','tools-gadgets',105)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Air Fryers','Air Fryers','air-fryers',105)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Microwave','Microwave','Microwave',105)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Blenders','Blenders','blenders',105)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('COVID-19 Testing Kits','COVID-19 Testing Kits','covid-19-testing-kit',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Face Masks','Face Masks','face-masks',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Medicine Cabinet','Medicine Cabinet','Medicine Cabinet',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pain Relievers','Pain Relievers','pain-relievers',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('First Aid','First Aid','first-aid',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Digestive Health','Digestive Health','digestive-health',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Home Health Care','Home Health Care','home-health-care',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Kid Healths','Kit Healths','kid-healths',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Eye Care ','Eye Care','eye-care',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Ear Care','Ear Care','ear-care',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Foot Care','Foot Care','foot-care',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Quit Smoking','Quit Smoking','quit-smoking',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Incontinence','Incotinence','incontinence',106)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Sexual Wellness','Sexual Wellness','sexual-wellness',106)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Toys','Toys','toy',107)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Stroller','Stroller','stroller',107)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Colthes','Clothes','clothes',107)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Nursery','Nursery','nursery',107)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Baby Health','Baby Health','Baby Health',107)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Feeding','Feeding','feeding',107)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Toddlers Room','Toddlers Room','toddlers-room',107)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Cough, Cold & Flu','Cough, Cold & Flu','cold-cold-flu',108)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Adrenaline','Andrenaline','Andrenaline',108)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Allergy,Sinus & Asthma','Allergy,Sinus & Asthma','allergy-sinus-asthma',108)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Vision Center','Tools & Gadgets','tools-gadgets',108)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Simple Refill','Air Fryers','air-fryers',108)

insert into payment (type, provider, account_no, expiry, accountID) values ('bankcard', 'Hilpert-Gleason', '5610754670440935', '2021-01-14', 703);
insert into addressSet (city, district, commune, accountID, address) values ('Anto', 'Equipment Operator', 'Metoprolol Tartrate', 48, '3 Loomis Plaza');