insert dbo.category(name , describe ,slug)
values ('Bakery','Bakery','bakery')
insert dbo.category(name , describe ,slug)
values ('Fruit & Vegetable','Fruit & Vegetable','fruit')
insert dbo.category(name , describe ,slug)
values ('Meet & Fish','Meet & Fish','meet')
insert dbo.category(name , describe ,slug)
values ('Drinks','Drinks','drink')
insert dbo.category(name , describe ,slug)
values ('Kitchen','Kitchen','kitchen')
insert dbo.category(name , describe ,slug)
values ('Special Nutrition','Special Nutrition','nutrition')
insert dbo.category(name , describe ,slug)
values ('Baby','Baby','baby')
insert dbo.category(name , describe ,slug)
values ('Pharmacy','Pharmacy','pharmacy')

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pancake','Pancake','pancake',1)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Muffins','Muffins','muffins',1)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Scornes','Scornes','scornes',1)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Bread','Bread','bread',1)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Bagel','Bagel','bagel',1)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pizza','Pizza','pizza',1)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Cookie','Cookie','cookie',1)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Vegetable','Vegetable','vegetable',2)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Fruit','Fruit','fruit',2)


insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Beef & Lamb','Beef & Lamb','beef-lamb',3)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Chicken','Chicken','chicken',3)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pork','Pork','pork',3)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Seafood','Seafood','seafood',3)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Organic','Organic','organic',3)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Bacon','Bacon','bacon',3)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Hot Dog & Sausage','Hot Dog & Sausage','hotdog-sausage',3)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Water','Water','water',4)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Soft Drinks','Soft Drinks','soft-drinks',4)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Fruit Juice','Fruit Juice','fruit-juice',4)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Sport Drinks','Sport Drinks','sport-drinks',4)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Energy Drinks','Energy Drinks','energy-drink',4)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Tea','Tea','tea',4)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Chocolate & Cocoa','Chocolate & Cocoa','chocolate-cocoa',4)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Cocktail','Cocktail','cocktail',4)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Chilled Beverages','Chilled Beverages','chilled-beverages',4)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Kitchen Appliances','Kitchen Appliances','kitchen-appliances',5)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Dining','Dining','dining',5)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pots & Pans','Pots & Pans','pots-pans',5)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Tools & Gadgets','Tools & Gadgets','tools-gadgets',5)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Air Fryers','Air Fryers','air-fryers',5)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Microwave','Microwave','Microwave',5)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Blenders','Blenders','blenders',5)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('COVID-19 Testing Kits','COVID-19 Testing Kits','covid-19-testing-kit',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Face Masks','Face Masks','face-masks',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Medicine Cabinet','Medicine Cabinet','Medicine Cabinet',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Pain Relievers','Pain Relievers','pain-relievers',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('First Aid','First Aid','first-aid',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Digestive Health','Digestive Health','digestive-health',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Home Health Care','Home Health Care','home-health-care',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Kid Healths','Kit Healths','kid-healths',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Eye Care ','Eye Care','eye-care',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Ear Care','Ear Care','ear-care',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Foot Care','Foot Care','foot-care',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Quit Smoking','Quit Smoking','quit-smoking',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Incontinence','Incotinence','incontinence',6)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Sexual Wellness','Sexual Wellness','sexual-wellness',6)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Toys','Toys','toy',7)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Stroller','Stroller','stroller',7)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Colthes','Clothes','clothes',7)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Nursery','Nursery','nursery',7)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Baby Health','Baby Health','Baby Health',7)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Feeding','Feeding','feeding',7)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Toddlers Room','Toddlers Room','toddlers-room',7)

insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Cough, Cold & Flu','Cough, Cold & Flu','cold-cold-flu',8)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Adrenaline','Andrenaline','Andrenaline',8)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Allergy,Sinus & Asthma','Allergy,Sinus & Asthma','allergy-sinus-asthma',8)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Vision Center','Tools & Gadgets','tools-gadgets',8)
insert dbo.subcategory(name , describe ,slug,categoryID)
values ('Simple Refill','Air Fryers','air-fryers',8)

insert into payment (type, provider, account_no, expiry, accountID) values ('bankcard', 'Hilpert-Gleason', '56754670440935', '2021-01-14', 703);
insert into addressSet (city, district, commune, accountID, address) values ('Anto', 'Equipment Operator', 'Metoprolol Tartrate', 48, '3 Loomis Plaza');